app:
  image: 10.100.198.200:5000/books-ms
  ports:
    - 8080
  environment:
    - SERVICE_NAME=books-ms

#app-blue:
#  environment:
#    - SERVICE_NAME=books-ms-blue
#  extends:
#    service: app
#
#app-green:
#  environment:
#    - SERVICE_NAME=books-ms-green
#  extends:
#    service: app

db:
  image: mongo
  ports:
    - 27017
  environment:
    - SERVICE_NAME=books-db
