app:
  image: 10.100.198.200:5000/books-ms
  ports:
    - 8080
  environment:
    - SERVICE_NAME=books-ms

db:
  image: mongo
  ports:
    - 27017
  log_driver: syslog
  log_opt:
    syslog-address: tcp://10.100.198.200:25826
    syslog-tag: books-db
  environment:
    - SERVICE_NAME=books-db
